export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const GET_ERROR = "GET_ERROR"
export const Create_CATEGORY = "Create_CATEGORY"
export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const Create_BRAND = "Create_BRAND"
export const Create_SUB_CATEGORY = "Create_SUB_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"
export const GET_ONE_BRAND = "GET_ONE_BRAND"
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const Create_NEW_USER = "Create_NEW_USER"


